# This is a basic workflow to help you get started with Actions

name: Semantoc Realease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # pasos realizados por mi 
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 14.17

      # intalacion de dependencies
      - name: Install Dependencies
        rund: yarn install

      - name: Build App
        rund: yarn build

      - name: Semantic Realease
        # variables => nombre:${{secrets_Nombre que le asisgnaste en githud}}
        env: 
          GITHUB_TOKEN: ${{secrets_GH_TOKEN}}
          NPM_TOKEN: ${{secrets_NPM_TOKEN}}
        rund: npx semantic-realease
